### ISSUE TITLE
Script inserts tabs

### ISSUE THREAD

**Issue by friederbluemle** [Carpetsmoker/sanitize_files#1]
Thanks for this script. I briefly looked at the source, and it looks like the default is to indent with 4 spaces (`indent_type='spaces', indent_width=4`). However, when I run the script in my source folder, it inserts tabs all over the place. Is this a known issue?

**Comment by arp242** [comment]
According to `./sanitize_files.py -h`:

```
  -i INDENT_TYPE, --indent-type INDENT_TYPE
                        indentation type; tabs or spaces; defaults to tabs
```

You probably looked at [this line](https://github.com/Carpetsmoker/sanitize_files/blob/master/sanitize_files.py#L43), but the real default is set from argparse [here](https://github.com/Carpetsmoker/sanitize_files/blob/master/sanitize_files.py#L151). Not sure why the function default is different...

**Comment by friederbluemle** [comment]
Oops. Sorry, yeah I just looked at the parameter default, not the help text. My bad.
